### ISSUE TITLE
Show how to install NetCDF libraries

### ISSUE THREAD

**Issue by JiaweiZhuang** [LiamBindle/Using-CMake-for-Beginners#1]
[Part 3](https://github.com/LiamBindle/An-Introduction-to-Using-CMake/wiki/Part-3:-Finding-dependencies) assumes that NetCDF libraries are installed, which might not be true for novice users.

The quickest way to install on Ubuntu:
```
sudo apt update && sudo apt install libnetcdf-dev libnetcdff-dev
```

`libnetcdf.so` is put under `/usr/lib/x86_64-linux-gnu`, so the cmake command would be:
```
cmake ../Part3 -DCMAKE_PREFIX_PATH="/usr/include;/usr/lib/x86_64-linux-gnu"
```

**Comment by LiamBindle** [comment]
Sorry @JiaweiZhuang, I haven't looked at this repo in a while and had notifications turned off.

Good point! I added a note to Part 3 for when `nc-config` errors.

Thanks, and sorry again that I missed this!

Liam
